model:
  class: learn.models.GeneralNN
  params:
    ensemble: false
    training:
      dx: -1
      du: -1
      dt: -1
      hid_width: 250
      hid_depth: 2
      probl: true
      activ: swish
      dropout: 0
      split: false
      mode: delta
      E: 5
      plot_loss: true
    optimizer:
      epochs: 33
      batch: 18
      name: Adam
      split: .8
      lr: .0025
      lr_schedule: [30,6]
      preprocess: true
      verbose: false
    datahandler:
      class: learn.utils.nn.ModelDataHandler
      params:
        X:
          class: sklearn.preprocessing.StandardScaler
          #          params:
          U:
            class: sklearn.preprocessing.MinMaxScaler
            params:
              feature_range: [-1.,1.]
          dX:
            class: sklearn.preprocessing.MinMaxScaler
            params:
              feature_range: [-1.,1.]
          sine_expand: []
