defaults:
  - robot: ???

model_path: ???
dimension: all
save: true

policy:
  mode: BASIC
  equil: [1500, 1500, 1500, 1500]
  min_pwm: [0,0,0,0]
  max_pwm: [3000, 3000, 3000, 3000]
  dt: .02

bo:
  iterations: 10
  sim: true

model:
  ensemble: false
  training:
    dx: -1
    du: -1
    dt: -1
    hid_width: 250
    hid_depth: 2
    probl: true
    activ: swish
    extra:
      dropout: 0
      split: false
      mode: delta
    E: 5
    plot_loss: true
  optimizer:
    epochs: 33
    batch: 18
    name: Adam
    split: .8
    lr: .0025
    lr_schedule: [30,6]
    preprocess: true
    verbose: false
