defaults:
  - robot: ???

#model_path: ???
dimension: all
save: true

policy:
  mode: BASIC
  params:
    equil: [1500, 1500, 1500, 1500]
    min_pwm: 0 #[0,0,0,0]
    max_pwm: 3000 #[3000, 3000, 3000, 3000]
    dt: .02
  pid:
    params:
      min_values: [0, 0]
      max_values: [300, 25]


bo:
  iterations: 15
  sim: true
  rollouts: 250
  variable_length: false
  max_length: 15


model:
  ensemble: false
  training:
    dx: -1
    du: -1
    dt: -1
    hid_width: 250
    hid_depth: 2
    probl: true
    activ: swish
    extra:
      dropout: 0
      split: false
      mode: delta
    E: 5
    plot_loss: true
  optimizer:
    epochs: 33
    batch: 18
    name: Adam
    split: .8
    lr: .0025
    lr_schedule: [30,6]
    preprocess: true
    verbose: false
